### ISSUE TITLE
ModuleNotFoundError: No module named 'utls'

### ISSUE THREAD

**Issue by shuowei** [m-jishnu/pypdl#4]
I am getting a `ModuleNotFoundError: No module named 'utls'` while trying to `from pypdl import Downloader`

Looking at the source code and commit history, I think this is caused by removing the dot in `main.py`

`from .utls import Multidown, Singledown, timestring`

Can you guys help take a look? From my experience, it should work without dot, so I am not sure what the root cause is ... 

Thanks,

**Comment by m-jishnu** [comment]
fixed it was as you said caused because i removed the dot for test and forgot to add it back, the dot is needed when using as a package
