### ISSUE TITLE
(UnicodeEncodeError, 'charmap' codec can't encode characters in position 1-31: character maps to <undefined>)

### ISSUE THREAD

**Issue by sanketkheni01** [m-jishnu/pypdl#5]
(UnicodeEncodeError, 'charmap' codec can't encode characters in position 1-31: character maps to <undefined>)

getting this error while downloading. btw I am on windows.

**Comment by m-jishnu** [comment]
hello,
can you tell me when does this error occurs and the full traceback of the error from console and if its possible the link of the data you were trying to download

**Comment by m-jishnu** [comment]
closing this as no info provided, feel free to re-open after providing the required info
